package com.yebur.backendorderly.employee;

import com.yebur.backendorderly.role.Role;
import com.yebur.backendorderly.role.RoleRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class EmployeeService implements EmployeeServiceInterface {

    private final EmployeeRepository employeeRepository;
    private final RoleRepository roleRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    @Transactional(readOnly = true)
    public List<EmployeeResponse> findAllEmployeesDTO() {
        return employeeRepository.findAll().stream()
                .map(EmployeeResponse::mapToResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<EmployeeResponse> findEmployeeDTOById(Long id) {
        return employeeRepository.findById(id)
                .map(EmployeeResponse::mapToResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<EmployeeResponse> findEmployeeDTOByEmail(String email) {
        return employeeRepository.findByEmail(email)
                .map(EmployeeResponse::mapToResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<EmployeeResponse> findCurrentEmployeeDTO(Authentication auth) {
        String email = auth.getName();
        return employeeRepository.findByEmail(email)
                .map(EmployeeResponse::mapToResponse);
    }

    private static final String TEMP_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    private static final SecureRandom RANDOM = new SecureRandom();

    private String generateTempPassword() {
        StringBuilder sb = new StringBuilder("Tmp");
        for (int i = 0; i < 6; i++) {
            sb.append(TEMP_CHARS.charAt(RANDOM.nextInt(TEMP_CHARS.length())));
        }
        return sb.toString();
    }

    @Override
    @Transactional
    public EmployeeResponse create(EmployeeRequest request) {
        if (employeeRepository.existsByEmail(request.getEmail())) {
            throw new IllegalArgumentException("Email already exists: " + request.getEmail());
        }

        Employee employee = new Employee();
        updateEmployeeFields(employee, request);
        String tempPwd = generateTempPassword();
        employee.setPassword(passwordEncoder.encode(tempPwd));
        employee.setMustChangePassword(true);
        // username auto-generated by caller (AuthController pattern) — set if not provided
        if (employee.getUsername() == null) {
            String base = (String.valueOf(request.getName().charAt(0)) + request.getLastname())
                    .toLowerCase().replaceAll("[^a-z0-9]", "");
            int i = 1;
            while (employeeRepository.existsByUsername(i == 1 ? base : base + (i - 1))) {
                if (!employeeRepository.existsByUsername(base)) break;
                i++;
            }
            employee.setUsername(employeeRepository.existsByUsername(base) ? base + i : base);
        }

        Employee saved = employeeRepository.save(employee);
        EmployeeResponse resp = EmployeeResponse.mapToResponse(saved);
        resp.setTempPassword(tempPwd);
        return resp;
    }

    @Override
    @Transactional
    public EmployeeResponse update(Long id, EmployeeRequest request) {
        Employee employee = employeeRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Employee not found with id: " + id));

        if (request.getEmail() != null && !request.getEmail().equals(employee.getEmail()) && employeeRepository.existsByEmail(request.getEmail())) {
            throw new IllegalArgumentException("Email already exists: " + request.getEmail());
        }

        updateEmployeeFields(employee, request);
        
        if (request.getPassword() != null && !request.getPassword().isBlank()) {
            employee.setPassword(passwordEncoder.encode(request.getPassword()));
        }

        Employee updatedEmployee = employeeRepository.save(employee);
        return EmployeeResponse.mapToResponse(updatedEmployee);
    }

    @Override
    @Transactional
    public void delete(Long id) {
        Employee employee = employeeRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Employee not found with id: " + id));
        employee.setStatus(EmployeeStatus.INACTIVE);
        employeeRepository.save(employee);
    }

    @Override
    @Transactional
    public String resetPassword(Long id) {
        Employee employee = employeeRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Employee not found with id: " + id));
        String tempPwd = generateTempPassword();
        employee.setPassword(passwordEncoder.encode(tempPwd));
        employee.setMustChangePassword(true);
        employeeRepository.save(employee);
        return tempPwd;
    }

    private void updateEmployeeFields(Employee employee, EmployeeRequest request) {
        if (request.getName() != null) {
            employee.setName(request.getName());
        }
        if (request.getLastname() != null) {
            employee.setLastname(request.getLastname());
        }
        if (request.getEmail() != null) {
            employee.setEmail(request.getEmail());
        }
        if (request.getPhoneNumber() != null) {
            employee.setPhoneNumber(request.getPhoneNumber());
        }
        if (request.getHireDate() != null) {
            employee.setHireDate(request.getHireDate());
        }

        if (request.getStatus() != null) {
            employee.setStatus(request.getStatus());
        } else if (employee.getStatus() == null) {
            employee.setStatus(EmployeeStatus.ACTIVE);
        }

        if (request.getRoles() != null) {
            Set<Role> roles = new HashSet<>(roleRepository.findAllById(request.getRoles()));
            employee.setRoles(roles);
        } else if (employee.getRoles() == null) {
            employee.setRoles(new HashSet<>());
        }
    }
}
